/*
 * swingDemo.java
 *
 * Created on __DATE__, __TIME__
 */

package project00;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;

import javax.imageio.ImageIO;


/**
 *
 * @author  __USER__
 */
public class swingDemo extends javax.swing.JFrame {

	/** Creates new form swingDemo 
	 * @throws IOException */
	public swingDemo() throws IOException {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 * @throws IOException 
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() throws IOException {

		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jPasswordField1 = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();
		jPasswordField2 = new javax.swing.JPasswordField();
		jSeparator1 = new javax.swing.JSeparator();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		Image image = ImageIO.read(this.getClass().getResource("/img/ÃÀÅ®.jpg"));
		this.setIconImage(image);
		this.setBackground(Color.yellow);
		
		
		
		

		jLabel1.setText("\u6587\u4ef6\u8def\u5f84\uff1a");

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		jButton1.setText("\u52a0\u5bc6");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel2.setText("\u79d8\u94a5\uff1a");

		jButton2.setText("\u89e3\u5bc6");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jPasswordField1.setText("jPasswordField1");

		jLabel3.setText("   \u754c           \u9762");

		jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jPasswordField2ActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(org.jdesktop.layout.GroupLayout.TRAILING,
						layout.createSequentialGroup()
								.add(68, 68, 68)
								.add(jButton1)
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED,
										226, Short.MAX_VALUE).add(jButton2)
								.add(45, 45, 45))
				.add(layout
						.createSequentialGroup()
						.add(76, 76, 76)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(jSeparator1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										329,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(layout
										.createSequentialGroup()
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.TRAILING)
												.add(jLabel2).add(jLabel1))
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(layout
														.createSequentialGroup()
														.add(48, 48, 48)
														.add(layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.LEADING)
																.add(layout
																		.createSequentialGroup()
																		.add(195,
																				195,
																				195)
																		.add(jPasswordField1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				0,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
																.add(jLabel3,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		105,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED,
																50,
																Short.MAX_VALUE))
												.add(layout
														.createSequentialGroup()
														.add(18, 18, 18)
														.add(layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.LEADING)
																.add(jTextField1,
																		org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																		275,
																		Short.MAX_VALUE)
																.add(jPasswordField2,
																		org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																		275,
																		Short.MAX_VALUE))))))
						.addContainerGap(24, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(32, 32, 32)
						.add(jLabel3)
						.add(36, 36, 36)
						.add(jSeparator1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(30, 30, 30)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(jLabel1)
								.add(jTextField1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										23,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPasswordField1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(10, 10, 10)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jLabel2)
								.add(jPasswordField2,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED, 40,
								Short.MAX_VALUE)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jButton2).add(jButton1)).add(35, 35, 35)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		System.out.println("¿×•FÊÇÉµ±Æ");
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new swingDemo().setVisible(true);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}